# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.paginated_result import PaginatedResult  # noqa: F401,E501
from swagger_server.models.product_array import ProductArray  # noqa: F401,E501
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: ProductArray=None, offset: int=None, limit: int=None, total: int=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param data: The data of this InlineResponse200.  # noqa: E501
        :type data: ProductArray
        :param offset: The offset of this InlineResponse200.  # noqa: E501
        :type offset: int
        :param limit: The limit of this InlineResponse200.  # noqa: E501
        :type limit: int
        :param total: The total of this InlineResponse200.  # noqa: E501
        :type total: int
        """
        self.swagger_types = {
            'data': ProductArray,
            'offset': int,
            'limit': int,
            'total': int
        }

        self.attribute_map = {
            'data': 'data',
            'offset': 'offset',
            'limit': 'limit',
            'total': 'total'
        }
        self._data = data
        self._offset = offset
        self._limit = limit
        self._total = total

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> ProductArray:
        """Gets the data of this InlineResponse200.


        :return: The data of this InlineResponse200.
        :rtype: ProductArray
        """
        return self._data

    @data.setter
    def data(self, data: ProductArray):
        """Sets the data of this InlineResponse200.


        :param data: The data of this InlineResponse200.
        :type data: ProductArray
        """

        self._data = data

    @property
    def offset(self) -> int:
        """Gets the offset of this InlineResponse200.

        Page offset  # noqa: E501

        :return: The offset of this InlineResponse200.
        :rtype: int
        """
        return self._offset

    @offset.setter
    def offset(self, offset: int):
        """Sets the offset of this InlineResponse200.

        Page offset  # noqa: E501

        :param offset: The offset of this InlineResponse200.
        :type offset: int
        """

        self._offset = offset

    @property
    def limit(self) -> int:
        """Gets the limit of this InlineResponse200.

        Page size limit  # noqa: E501

        :return: The limit of this InlineResponse200.
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit: int):
        """Sets the limit of this InlineResponse200.

        Page size limit  # noqa: E501

        :param limit: The limit of this InlineResponse200.
        :type limit: int
        """

        self._limit = limit

    @property
    def total(self) -> int:
        """Gets the total of this InlineResponse200.

        Total number of records across all pages  # noqa: E501

        :return: The total of this InlineResponse200.
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total: int):
        """Sets the total of this InlineResponse200.

        Total number of records across all pages  # noqa: E501

        :param total: The total of this InlineResponse200.
        :type total: int
        """

        self._total = total
